version: '3.8'

services:
  nginx-main:
    build:
      context: dockerfiles/nginx
    ports:
      - "80:80"
    volumes:
      - app_files:/var/www/html/
  php-service:  
    build:
      context: dockerfiles/php
    volumes:
      - app_files:/var/www/html/
  app_files_service:
    build:
      context: dockerfiles/app_files_service
      dockerfile: Dockerfile.app_files_service
    volumes:
      - app_files:/var/www/html
volumes:
  app_files: