version: '3.8'

services:
  nginx-main:
    image: zloyejikad/test-app-file:${VERSION_NUMBER}
    ports:
      - "80:80"
    volumes:
      - app_files:/var/www/html/
    depends_on:
      - app_files_service
  php-service:  
    image: zloyejikad/test-nginx:${VERSION_NUMBER}
    volumes:
      - app_files:/var/www/html/
    depends_on:
      - app_files_service
  app_files_service:
    image: zloyejikad/test-php:${VERSION_NUMBER}
    volumes:
      - app_files:/var/www/html
  db_service:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB-PASSWORD}
  db_control:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8081:80"
volumes:
  app_files: