version: '3.8'

services:
  nginx-main:
    build: dockerfiles/nginx
    ports:
      - "80:80"
    volumes:
      - ./dockerfiles/app/:/var/www/html/
  php-service:  
    build: dockerfiles/php
    volumes:
      - ./dockerfiles/app/:/var/www/html/